### ISSUE TITLE
keepOpen does not work

### ISSUE THREAD

**Issue by jlAlice** [i-net-software/dokuwiki-plugin-popupviewer#11]
"keepOpen" option does not keep popup page open if clicking link in it
Popupviewer php script renders `{{popup>test2?keepOpen}}` as:

`<a style="border: 1px solid #ccc; padding: 0 3px;" href="/doku.php?id=wiki:test2" data-popupviewer="{&quot;width&quot;:&quot;keepopen&quot;,&quot;id&quot;:&quot;wiki:test2&quot;}" class="wikilink1" >test2</a>`

I suppose the popupviewer js script does not get parameters from "data-popupviewer=".
I do not know programming, maybe the problem is somewhere in viewer.php about the line [146](https://github.com/i-net-software/dokuwiki-plugin-popupviewer/blob/master/syntax/viewer.php#L146).

I tried new installation of dokuwiki and old version of the popupviewer plug-in (of 2016-06) - the problem is the same.

**Comment by jeppsipepsi** [comment]
I have the same problem - after adding "keepOpen", links inside the popup window opens in the same window I originally opened the popup from, not inside the popup itself. I'm using DokuWiki Frusterick Manners
