### ISSUE TITLE
Render external web pages

### ISSUE THREAD

**Issue by GJRobert** [i-net-software/dokuwiki-plugin-popupviewer#15]
I like the AJAX/loading on demand nature of this popup viewer.

I have been looking for a "load on demand" iframe external page viewer so to lower the payload of loading a page with a couple of iframes, but without success. If I hope to extend this popupviewer plugin, where should look at?

**Comment by gamma** [comment]
Phu ...

Have a look at the action.php where the plugin looks for the ID. Instead of loading the HTML for the ID, try to use the DokuHTTPClient and fetch your external content.
