### ISSUE TITLE
popup>image stopped displaying the image

### ISSUE THREAD

**Issue by rellampec** [i-net-software/dokuwiki-plugin-popupviewer#19]
With this week's upgrade to [Hogfather](https://www.dokuwiki.org/changes), I did some testing and when clicking on the image, the popup starts, but the image does not get to display. It keeps as if still in progress.

One of the dokuwiki upgrade is:

-  Defer the loading of JavaScript to improve initial page loads :!:

Not quite sure if that had anything to do with it, although doesn't seem related.

btw, a new message of not having updated the plug-in in more than 2 years appeared in your [plugin-info on dokuwiki](https://www.dokuwiki.org/plugin:popupviewer)

**Comment by gamma** [comment]
Please check the latest repository version
