### ISSUE TITLE
Popup window too small for content with "Hogfather" RC2

### ISSUE THREAD

**Issue by todmorrison** [i-net-software/dokuwiki-plugin-popupviewer#20]
i just upgraded to Release rc2-2020-06-01 "Hogfather" RC2 and checked some pages. One case where I have a popup the loads another page successfully loads the page, but into a window that is only a single line and a few characters wide.

**Comment by todmorrison** [comment]
Wrong plugin

**Comment by DeedJayB** [comment]
Hi,
On my wiki, the popup appears but keep loading the picture.

I also noticed that on pages where there's a popupViewer call, if you modify them, then they appear blank. If I deactivate the plugin, the page appears as usual.

**Comment by gamma** [comment]
Have you updated both, the Plugin and DW? Which versions are you running?

**Comment by gamma** [comment]
The resize Issue should be fixed with 9b3d03d81fc647ba9fdb66eff37f1dc6ccbe964b

**Comment by todmorrison** [comment]
Odd. Now it no longer works as a popup. It simply acts as a normal link to the other page.

**Comment by gamma** [comment]
Have you checked the javascript cache? It may be needed to clean it from the wiki and the browser.

**Comment by todmorrison** [comment]
How do I clear the wiki cache? II tried with a different browser and got the same behavior.

**Comment by gamma** [comment]
Ok, strange. You are still on Hogfather RC2? What about RC3?

The cache can be cleared using the Cache Eraser Plugin, but you can modify the configuration using the config editor too - modify a boolean, save, reset boolean.

**Comment by todmorrison** [comment]
I actually just upgraded to RC3. Tried the "modify a boolean, save, reset boolean" .... no change.

**Comment by todmorrison** [comment]
The relevant anchor tag looks like this;

<a href="/dokuwiki/doku.php?id=cooking:recipes:quicksoak" data-popupviewer="{&quot;id&quot;:&quot;cooking:recipes:quicksoak&quot;}" class="wikilink1 popupviewer" >

**Comment by gamma** [comment]
do you have a public link for me to check?

**Comment by todmorrison** [comment]
Sorry, I don't ... It's just a little wiki running off a NAS in my local network

**Comment by gamma** [comment]
Ok, the link should look different; can you open the Developer Console (F12 in Chrome) and check if there are any JavaSCript errors?

**Comment by todmorrison** [comment]
Yes, it looks like there is an "Uncaught SyntaxError: Unexpected identifier". I'm not sure I'm getting to the error in the tool right, but it *looks* like it's pointing at this:

popupData.call=popupData.call||'_popup_load_image_meta';var img=new Image()img.onload=function(){var image=$(img);

**Comment by todmorrison** [comment]
Searching for and manually editing the cached java script file to add a semicolon between "var img=new Image()" and "img.onload=function()" seems to have resolved the issue for the moment, but I'm not sure how it that's a permanent fix since I don't know how it got that way.

**Comment by todmorrison** [comment]
I think I've found it. In "script.js" line 165 there's no terminating semicolon, i.e. it looks like:

                var img = new Image()
