### ISSUE TITLE
Not adhering to ACLs

### ISSUE THREAD

**Issue by splitbrain** [i-net-software/dokuwiki-plugin-popupviewer#23]
A user in the forum writes, that this plugin is ignoring the ACLs. I added a security note on the plugin page for now.

https://forum.dokuwiki.org/d/19016-200-bounty-randomizer-extension/9

Please note, that I haven't verified this myself, so feel free to close this issue and remove the warning again if it's bogus.

**Comment by Stikus** [comment]
@gamma Thanks for fix but you should push new release because Dokuwiki still don't know about this fix:
![image](https://user-images.githubusercontent.com/41360525/145837857-5f9fc62b-8d6a-4a2d-92c7-e4bea119f15f.png)
