### ISSUE TITLE
popup shows only partial image

### ISSUE THREAD

**Issue by kmotors** [i-net-software/dokuwiki-plugin-popupviewer#4]
Running Dokuwiki 2014-09-29b "Hrun" and installed fresh 2014 version of popupviewer plugin. The popup image that appears when the link is clicked looks like only the first few pixels of the image (see attached screenshot). The size dimensions also do not seem to work; that is, the partial image that appears is the same regardless of size parameters.

A prior version of popupviewer worked fine with an earlier version of Dokuwiki.

![screen shot 2015-01-23 at 8 38 21 am](https://cloud.githubusercontent.com/assets/10670419/5875451/3a95733a-a2db-11e4-907d-2d3a1f57a18b.png)

**Comment by gamma** [comment]
Are there any JavaScript errors in your browser console?

**Comment by kmotors** [comment]
How do I check for errors? No error messages appear on screen.

**Comment by gamma** [comment]
Ok, please see this fixed in 7a64d69cdc998cf35d70c94ef913d470494eb0c9 - Just reinstall from the Extension Manager.

**Comment by kmotors** [comment]
Great! Thanks ... works fine now.
