### ISSUE TITLE
not compatible with plugin:docnavigation?

### ISSUE THREAD

**Issue by rwoldu** [i-net-software/dokuwiki-plugin-popupviewer#5]
Popupviewer doesn't work when docnavigation is used in the page, too.
Is there maybe a workaround?

Thanks in advance.

**Comment by gamma** [comment]
I do not know of any problems, so what exactly is the problem? Are there any JavaScript errors in the console?

**Comment by rwoldu** [comment]
Hello,

the whole structure changes when I add the syntax of popupviewer to my source: the links of docnavigation are shifted (instead in the beginning and in the end,they are placed in the middle of the text. Here are 2 screenshots:

![example-docnavigation-popupviewer](https://cloud.githubusercontent.com/assets/12166778/8036624/5834095e-0df9-11e5-9b9b-a7323993814f.JPG)


![example-docnavigation-popupviewer-source](https://cloud.githubusercontent.com/assets/12166778/8036633/68c222c4-0df9-11e5-9282-7d4d157af580.JPG)

**Comment by gamma** [comment]
Please check the CSS.

**Comment by rwoldu** [comment]
HI, thanks for the tip.Greetings
