### ISSUE TITLE
Does not work with relative paths

### ISSUE THREAD

**Issue by greenseeker** [i-net-software/dokuwiki-plugin-popupviewer#8]
For example, if I'm editing page :playground:playground and I want to insert image :playground:sample.png...

This won't work:
```{{popup>sample.png}}```

I have to do this:
```{{popup>:playground:sample.png}}```

**Comment by gamma** [comment]
Please check if this works with the new version.

**Comment by greenseeker** [comment]
Yes, I just reinstalled and was able to specify an image via relative path.

Thank you.
